spring.application.name=demo
server.tomcat.threads.max=400
server.tomcat.accept-count=1000
server.tomcat.max-connections=8192
server.tomcat.processor-cache=200

rate-limit.tiers.FREE.capacity=100
rate-limit.tiers.FREE.refill-rate=0.0277777778
rate-limit.tiers.PRO.capacity=1000
rate-limit.tiers.PRO.refill-rate=0.2777777778
rate-limit.tiers.ENTERPRISE.capacity=5000
rate-limit.tiers.ENTERPRISE.refill-rate=1.3888888889
rate-limit.tiers.UNLIMITED.capacity=9223372036854775807
rate-limit.tiers.UNLIMITED.refill-rate=9223372036854775807
